package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildA'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildA")) {
    params {
        add {
            param("env.GIT_CURL_VERBOSE", "/Users/mikhail.efremov/Downloads/git_trace.log")
        }
        add {
            param("env.GIT_TRACE", "/Users/mikhail.efremov/Downloads/git_trace.log")
        }
    }

    features {
        val feature1 = find<PullRequests> {
            pullRequests {
                id = "BUILD_EXT_3"
                vcsRootExtId = "TestProject_HttpsGithubComDy1ngTcTestProjectRefsPullMerge"
                provider = github {
                    authType = vcsRoot()
                    filterAuthorRole = PullRequests.GitHubRoleFilter.MEMBER
                }
            }
        }
        feature1.apply {
            vcsRootExtId = "TestProject_HttpsGithubComDy1ngTcTestProjectMasterWPullRequests"
        }
    }
}
